/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingsw;
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author dario
 */
public class EmettiIngiunzioneForm extends javax.swing.JFrame {
    private EmettiIngiunzioneController controller;
    String idIngiunzione;
    String idUtenza;
    /**
     * Creates new form EmettiIngiunzioneForm
     */
    public EmettiIngiunzioneForm(EmettiIngiunzioneController controller) {
        this.controller=controller;
       
        setResizable(false);
        initComponents();
    }
    
  

    
    public void show(ResultSet listaIngiunzioni) {
        this.nProtocolloButton.setEnabled(false);
        this.emettiButton.setEnabled(false);
        setIngiunzioni(listaIngiunzioni);
    }
    public void setIngiunzioni(ResultSet rst) {
      DefaultTableModel dtm = new DefaultTableModel(); 
      try {
       ResultSetMetaData meta = rst.getMetaData();
       int columns = meta.getColumnCount();
       for (int i = 1; i <= columns; i++){
            dtm.addColumn(meta.getColumnName(i));
        }
       
        Object [] rowData = new Object[columns];
       
        while(rst.next()) {  
                for (int i = 0; i < columns; i++)
                {
                    rowData[i] = rst.getObject(i+1);
                }
            dtm.addRow(rowData);  
                   
        }
      }
      catch(SQLException e){
          JOptionPane.showMessageDialog(this, "Non è stato possibile caricare la tabella","Errore", JOptionPane.ERROR_MESSAGE);
      }
       ingiunzioniTable.setModel(dtm);  
    }
    
    public void resetIngiunzioni() {
        ResultSet ingiunzioni = controller.resetIngiunzioni();
        setIngiunzioni(ingiunzioni);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nProtocolloTextField = new javax.swing.JTextField();
        nProtocolloButton = new javax.swing.JButton();
        emettiButton = new javax.swing.JButton();
        indietroButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingiunzioniTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleziona l'ingiunzione da emettere");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 188, 40));

        nProtocolloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nProtocolloTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nProtocolloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 175, 41));

        nProtocolloButton.setText("Genera n protocollo");
        nProtocolloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nProtocolloButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nProtocolloButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 143, 41));

        emettiButton.setText("Emetti Ingiunzione");
        emettiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emettiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(emettiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 171, 44));

        indietroButton.setText("Indietro");
        indietroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(indietroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 170, 50));

        ingiunzioniTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ingiunzioniTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingiunzioniTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ingiunzioniTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 362, 89));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSoftSmall.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 280, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whiteAndBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 431, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingiunzioniTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingiunzioniTableMouseClicked
        emettiButton.setEnabled(false);
        nProtocolloTextField.setText("");
        idIngiunzione = selectIngiunzione();
        idUtenza = selectUtenza();
        this.nProtocolloButton.setEnabled(true);
    }//GEN-LAST:event_ingiunzioniTableMouseClicked

    private void nProtocolloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nProtocolloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nProtocolloTextFieldActionPerformed

    private void nProtocolloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nProtocolloButtonActionPerformed
        nProtocolloTextField.setText(controller.generaProtocollo(idIngiunzione,idUtenza));
        nProtocolloButton.setEnabled(false);
        emettiButton.setEnabled(true);
    }//GEN-LAST:event_nProtocolloButtonActionPerformed

    private void emettiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emettiButtonActionPerformed
        controller.pushedEmetti();
        emettiButton.setEnabled(false);
        resetIngiunzioni();
    }//GEN-LAST:event_emettiButtonActionPerformed

    private void indietroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroButtonActionPerformed
        controller.pushedIndietro();
    }//GEN-LAST:event_indietroButtonActionPerformed
    
    private String selectIngiunzione() {
        int index = ingiunzioniTable.getSelectedRow();
        TableModel model = ingiunzioniTable.getModel();
        return model.getValueAt(index, 0).toString();
    }
    private String selectUtenza() {
         int index = ingiunzioniTable.getSelectedRow();
        TableModel model = ingiunzioniTable.getModel();
        return model.getValueAt(index, 1).toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmettiIngiunzioneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmettiIngiunzioneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmettiIngiunzioneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmettiIngiunzioneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emettiButton;
    private javax.swing.JButton indietroButton;
    private javax.swing.JTable ingiunzioniTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nProtocolloButton;
    private javax.swing.JTextField nProtocolloTextField;
    // End of variables declaration//GEN-END:variables
}
