/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingsw;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Date;

/**
 *
 * @author dario
 */
public class RicercaIngiunzioneForm extends javax.swing.JFrame {
    private RicercaIngiunzioneController controller;
    private ResultSet ingiunzioni;
    /**
     * Creates new form RicercaIngiunzioneForm
     */
    public RicercaIngiunzioneForm(RicercaIngiunzioneController c) {
        setResizable(false);
        initComponents();
        controller=c;
        ricercaButton.setEnabled(false);
        ricercaButton.setEnabled(false);
        sospendiButton.setEnabled(false);
        cancellaButton.setEnabled(false);
        pdfButton.setEnabled(false);
        inizioDataPicker.setFormats("yyyy-MM-dd");
        Date dateI = new Date(117,00,01);
        Date date = new Date();
        inizioDataPicker.setDate(dateI);
        fineDataPicker.setFormats("yyyy-MM-dd");
        fineDataPicker.setDate(date);
      
        
    }
    public void resetButton() {
        ricercaButton.setEnabled(false);
        ricercaButton.setEnabled(false);
        sospendiButton.setEnabled(false);
        cancellaButton.setEnabled(false);
        modificaButton.setEnabled(false);
        pdfButton.setEnabled(false);
    }
    public void setIngiunzioni(ResultSet rst) {
    if(rst!=null) {
      DefaultTableModel dtm = new DefaultTableModel(); 
      try {
       ResultSetMetaData meta = rst.getMetaData();
       int columns = meta.getColumnCount();
       for (int i = 1; i <= columns; i++){
            dtm.addColumn(meta.getColumnName(i));
        }
       
        Object [] rowData = new Object[columns];
       
        while(rst.next()) {  
                for (int i = 0; i < columns; i++)
                {
                    rowData[i] = rst.getObject(i+1);
                }
            dtm.addRow(rowData);  
                   
        }
      }
      catch(SQLException e){
          
      }
       ingiunzioniTable.setModel(dtm);  
    }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ingiunzioniTable = new javax.swing.JTable();
        sospendiButton = new javax.swing.JButton();
        ricercaButton = new javax.swing.JButton();
        cancellaButton = new javax.swing.JButton();
        pdfButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        cognomeTextField = new javax.swing.JTextField();
        idUtenteTextField = new javax.swing.JTextField();
        idIngiunzioneTextField = new javax.swing.JTextField();
        indirizzoTextField = new javax.swing.JTextField();
        cittaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inizioDataPicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fineDataPicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel10 = new javax.swing.JLabel();
        modificaButton = new javax.swing.JButton();
        indietroButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingiunzioniTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingiunzioniTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ingiunzioniTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 420, 250));

        sospendiButton.setText("Sospendi");
        sospendiButton.setEnabled(false);
        sospendiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sospendiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sospendiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 108, 41));

        ricercaButton.setText("Ricerca");
        ricercaButton.setEnabled(false);
        ricercaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ricercaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ricercaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 110, 40));

        cancellaButton.setText("Cancella");
        cancellaButton.setEnabled(false);
        cancellaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancellaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 108, 41));

        pdfButton.setText("Genera PDF");
        pdfButton.setEnabled(false);
        pdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pdfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 110, 40));

        jLabel1.setText("Seleziona parametri ricerca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, 24));

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        nomeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeTextFieldKeyPressed(evt);
            }
        });
        getContentPane().add(nomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 138, -1));

        cognomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cognomeTextFieldActionPerformed(evt);
            }
        });
        cognomeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cognomeTextFieldKeyPressed(evt);
            }
        });
        getContentPane().add(cognomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 138, -1));

        idUtenteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUtenteTextFieldActionPerformed(evt);
            }
        });
        idUtenteTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idUtenteTextFieldKeyPressed(evt);
            }
        });
        getContentPane().add(idUtenteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 138, -1));

        idIngiunzioneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idIngiunzioneTextFieldKeyPressed(evt);
            }
        });
        getContentPane().add(idIngiunzioneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 140, -1));

        indirizzoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indirizzoTextFieldActionPerformed(evt);
            }
        });
        indirizzoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                indirizzoTextFieldKeyPressed(evt);
            }
        });
        getContentPane().add(indirizzoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 138, -1));

        cittaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cittaTextFieldKeyPressed(evt);
            }
        });
        getContentPane().add(cittaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 138, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 40, 24));

        jLabel3.setText("Cognome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 24));

        jLabel4.setText("idUtente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, 24));

        jLabel5.setText("idIngiunzione");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 24));

        jLabel6.setText("Indirizzo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 60, 24));

        jLabel7.setText("Città");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 40, 24));

        inizioDataPicker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inizioDataPickerMouseClicked(evt);
            }
        });
        inizioDataPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inizioDataPickerActionPerformed(evt);
            }
        });
        inizioDataPicker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inizioDataPickerKeyPressed(evt);
            }
        });
        getContentPane().add(inizioDataPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel8.setText("Data");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 41, 22));

        jLabel9.setText("Inizio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 41, 22));

        fineDataPicker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fineDataPickerKeyPressed(evt);
            }
        });
        getContentPane().add(fineDataPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel10.setText("Fine");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 41, 22));

        modificaButton.setText("Modifica");
        modificaButton.setEnabled(false);
        modificaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(modificaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 108, 41));

        indietroButton.setText("Indietro");
        indietroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(indietroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 105, 41));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSoftSmall.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 90));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whiteAndBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ricercaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ricercaButtonActionPerformed
        resetButton();
        String nome=nomeTextField.getText();
        String cognome=cognomeTextField.getText();
        String indirizzo=indirizzoTextField.getText();
        String citta=cittaTextField.getText();
        String idIngiunzione=idIngiunzioneTextField.getText();
        String idUtente=idUtenteTextField.getText();
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        String inizio = dateFormat.format(inizioDataPicker.getDate());
        String fine = dateFormat.format(fineDataPicker.getDate());
        
      
        ingiunzioni=controller.pushedRicerca(nome, cognome, idUtente, idIngiunzione, indirizzo, citta, inizio, fine);
        setIngiunzioni(ingiunzioni);
    }//GEN-LAST:event_ricercaButtonActionPerformed

    private void indirizzoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indirizzoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indirizzoTextFieldActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        resetButton();
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void modificaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaButtonActionPerformed
        String id = selectIngiunzione();
        controller.pushedModifica(id);
    }//GEN-LAST:event_modificaButtonActionPerformed

    
    private void nomeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextFieldKeyPressed
       checkIfEnableRicerca();
    }//GEN-LAST:event_nomeTextFieldKeyPressed

    private void cognomeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cognomeTextFieldKeyPressed
         checkIfEnableRicerca();
    }//GEN-LAST:event_cognomeTextFieldKeyPressed

    private void ingiunzioniTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingiunzioniTableMouseClicked
      checkSospensione();
      checkEmissione();
      modificaButton.setEnabled(true);
      pdfButton.setEnabled(true);
    }//GEN-LAST:event_ingiunzioniTableMouseClicked

    private void cognomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cognomeTextFieldActionPerformed
       resetButton();
    }//GEN-LAST:event_cognomeTextFieldActionPerformed

    private void sospendiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sospendiButtonActionPerformed
        String ingiunzione = selectIngiunzione();
        controller.pushedSospendi(ingiunzione);
        System.out.println(ingiunzione);
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String inizio = dateFormat.format(inizioDataPicker.getDate());
        String fine = dateFormat.format(fineDataPicker.getDate());
        ingiunzioni=controller.pushedRicerca("","","",ingiunzione,"","",inizio,fine);
        setIngiunzioni(ingiunzioni);
        sospendiButton.setEnabled(false);
    }//GEN-LAST:event_sospendiButtonActionPerformed

    private void cancellaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellaButtonActionPerformed
        String ingiunzione = selectIngiunzione();
        controller.pushedCancella(ingiunzione);
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String inizio = dateFormat.format(inizioDataPicker.getDate());
        String fine  = dateFormat.format(fineDataPicker.getDate());
        ingiunzioni=controller.pushedRicerca("","","",ingiunzione,"","",inizio,fine);
        setIngiunzioni(ingiunzioni);
        cancellaButton.setEnabled(false);
    }//GEN-LAST:event_cancellaButtonActionPerformed

    private void indietroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroButtonActionPerformed
        controller.pushedIndietro();
    }//GEN-LAST:event_indietroButtonActionPerformed

    private void idUtenteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUtenteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUtenteTextFieldActionPerformed

    private void idUtenteTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idUtenteTextFieldKeyPressed
         checkIfEnableRicerca();
    }//GEN-LAST:event_idUtenteTextFieldKeyPressed

    private void idIngiunzioneTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idIngiunzioneTextFieldKeyPressed
        checkIfEnableRicerca();
    }//GEN-LAST:event_idIngiunzioneTextFieldKeyPressed

    private void indirizzoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indirizzoTextFieldKeyPressed
        checkIfEnableRicerca();
    }//GEN-LAST:event_indirizzoTextFieldKeyPressed

    private void cittaTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cittaTextFieldKeyPressed
       checkIfEnableRicerca();
    }//GEN-LAST:event_cittaTextFieldKeyPressed

    private void inizioDataPickerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inizioDataPickerKeyPressed
            ricercaButton.setEnabled(true);
    }//GEN-LAST:event_inizioDataPickerKeyPressed

    private void fineDataPickerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fineDataPickerKeyPressed
          ricercaButton.setEnabled(true);
    }//GEN-LAST:event_fineDataPickerKeyPressed

    private void inizioDataPickerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inizioDataPickerMouseClicked
         ricercaButton.setEnabled(true);
    }//GEN-LAST:event_inizioDataPickerMouseClicked

    private void inizioDataPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inizioDataPickerActionPerformed
       ricercaButton.setEnabled(true);
    }//GEN-LAST:event_inizioDataPickerActionPerformed

    private void pdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfButtonActionPerformed
        String idIngiunzione=selectIngiunzione();
        controller.pushedPDF(idIngiunzione);
        resetButton();
    }//GEN-LAST:event_pdfButtonActionPerformed
    private void checkSospensione() {
        String stato = selectStato();
        if(stato.equals("E")) {
            sospendiButton.setEnabled(true);
        }
        else
            sospendiButton.setEnabled(false);
    }
    private void checkEmissione() {
        String stato = selectStato();
        if(stato.equals("NE")) {
            cancellaButton.setEnabled(true);
        }
        else
            cancellaButton.setEnabled(false);
    }
    private String selectStato() {
        int index = ingiunzioniTable.getSelectedRow();
        TableModel model = ingiunzioniTable.getModel();
        return model.getValueAt(index, 3).toString();
    }
    private String selectIngiunzione() {
        int index = ingiunzioniTable.getSelectedRow();
        TableModel model = ingiunzioniTable.getModel();
        return model.getValueAt(index, 0).toString();
    }
    
     private void checkIfEnableRicerca() {
         if(nomeTextField.getText().length()<=0 && cognomeTextField.getText().length()<=0 &&idUtenteTextField.getText().length()<=0 && indirizzoTextField.getText().length()<=0 && cittaTextField.getText().length()<=0)
            ricercaButton.setEnabled(false);
        else
            ricercaButton.setEnabled(true);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RicercaIngiunzioneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RicercaIngiunzioneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RicercaIngiunzioneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RicercaIngiunzioneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancellaButton;
    private javax.swing.JTextField cittaTextField;
    private javax.swing.JTextField cognomeTextField;
    private org.jdesktop.swingx.JXDatePicker fineDataPicker;
    private javax.swing.JTextField idIngiunzioneTextField;
    private javax.swing.JTextField idUtenteTextField;
    private javax.swing.JButton indietroButton;
    private javax.swing.JTextField indirizzoTextField;
    private javax.swing.JTable ingiunzioniTable;
    private org.jdesktop.swingx.JXDatePicker inizioDataPicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificaButton;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JButton pdfButton;
    private javax.swing.JButton ricercaButton;
    private javax.swing.JButton sospendiButton;
    // End of variables declaration//GEN-END:variables
}
