/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingsw;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Dario
 */
public class SelezionaEvasoreForm extends javax.swing.JFrame {

    private String idEvasore = null;
    private CreaIngiunzioneController controll;
    public SelezionaEvasoreForm(CreaIngiunzioneController c) {
        controll=c;
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        evasoreTable = new javax.swing.JTable();
        evasoreTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        avantiButton = new javax.swing.JButton();
        indietroButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        evasoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        evasoreTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evasoreTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(evasoreTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, 630, 208));

        evasoreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evasoreTextFieldActionPerformed(evt);
            }
        });
        evasoreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                evasoreTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                evasoreTextFieldKeyReleased(evt);
            }
        });
        getContentPane().add(evasoreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 130, 351, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cerca evasore inserendo qualsiasi dato");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 90, -1, -1));

        avantiButton.setText("Avanti");
        avantiButton.setEnabled(false);
        avantiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avantiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(avantiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 418, 114, 35));

        indietroButton.setText("Indietro");
        indietroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(indietroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 418, 102, 35));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSoftSmall.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whiteAndBlue.jpg"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void evasoreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evasoreTextFieldActionPerformed
       
    }//GEN-LAST:event_evasoreTextFieldActionPerformed

    private void evasoreTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_evasoreTextFieldKeyPressed
      
    }//GEN-LAST:event_evasoreTextFieldKeyPressed

    private void evasoreTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_evasoreTextFieldKeyReleased
         String dato = evasoreTextField.getText();
         controll.sendDatoInserito(dato);
    }//GEN-LAST:event_evasoreTextFieldKeyReleased

    private void avantiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avantiButtonActionPerformed
        submit();
    }//GEN-LAST:event_avantiButtonActionPerformed

    private void evasoreTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evasoreTableMouseClicked
       /* int index = evasoreTable.getSelectedRow();
        TableModel model = evasoreTable.getModel();
        cF=(model.getValueAt(index, 2).toString()); */
       selected();
    }//GEN-LAST:event_evasoreTableMouseClicked

    private void indietroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroButtonActionPerformed
        controll.pushedIndietroEvasore();
    }//GEN-LAST:event_indietroButtonActionPerformed
    private void submit() {
        idEvasore= getEvasore();
        controll.submit(idEvasore);
    }
    private String getEvasore() {
        int index = evasoreTable.getSelectedRow();
        TableModel model = evasoreTable.getModel();
        return model.getValueAt(index, 0).toString(); 
    }
    private void selected() {
        if(!avantiButton.isEnabled())
            avantiButton.setEnabled(true);
    }
    public void setEvasori(ResultSet rst) {
      DefaultTableModel dtm = new DefaultTableModel(); 
      if(rst!=null) {
     
      try {
       ResultSetMetaData meta = rst.getMetaData();
         int columns = meta.getColumnCount();
       
      
       for (int i = 1; i <= columns; i++){
            dtm.addColumn(meta.getColumnName(i));
        }
       
        Object [] rowData = new Object[columns];
       
        while(rst.next()) {  
                for (int i = 0; i < columns; i++)
                {
                    rowData[i] = rst.getObject(i+1);
                }
            dtm.addRow(rowData);  
                   
        }
      }
      catch(SQLException e){
          
      }
       evasoreTable.setModel(dtm);  
      }
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avantiButton;
    private javax.swing.JLabel back;
    private javax.swing.JTable evasoreTable;
    private javax.swing.JTextField evasoreTextField;
    private javax.swing.JButton indietroButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
