/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingsw;

/**
 *
 * @author Dario
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuFormT
     */
    public MenuForm() {
        setResizable(false);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creaIngiunzioneButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EmmettiIngiunzioneButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        creaIngiunzioneButton.setText("Crea Ingiunzione");
        creaIngiunzioneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaIngiunzioneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creaIngiunzioneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 265, 60));

        jButton2.setText("Ricerca/Gestisci Ingiunzione");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 265, 60));

        EmmettiIngiunzioneButton.setText("Emmetti Ingiunzione");
        EmmettiIngiunzioneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmmettiIngiunzioneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EmmettiIngiunzioneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 265, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSoft2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 360, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whiteAndBlue.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 431, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creaIngiunzioneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaIngiunzioneButtonActionPerformed
        CreaIngiunzioneController controll = new CreaIngiunzioneController();
        controll.start();
    }//GEN-LAST:event_creaIngiunzioneButtonActionPerformed

    private void EmmettiIngiunzioneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmmettiIngiunzioneButtonActionPerformed
        EmettiIngiunzioneController controll = new EmettiIngiunzioneController();
        controll.start();
        
    }//GEN-LAST:event_EmmettiIngiunzioneButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RicercaIngiunzioneController c = new RicercaIngiunzioneController(this);
        this.setVisible(false);
        c.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmmettiIngiunzioneButton;
    private javax.swing.JButton creaIngiunzioneButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
